export const ADD_COMMENT = 'ADD_COMMENT';
export const HEURISTICS_LOADING = 'HEURISTICS_LOADING';
export const HEURISTICS_FAILED= 'HEURISTICS_FAILED';
export const ADD_HEURISTICS= 'ADD_HEURISTICS';
export const ADD_COMMENTS='ADD_COMMENTS';
export const COMMENTS_FAILED='COMMENTS_FAILED';